### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by SeanMollet** [Ingenic-community/Cloner#1]
The version posted here is quite a ways behind the latest. Any chance you could update it?

Thanks.

**Comment by ReimuNotMoe** [comment]
I'm a bit curious, so you mean that you know there are new versions available but unable to get them?

**Comment by SeanMollet** [comment]
Correct. They fixed their FTP last night though, so the newer versions are once again available. I can't PR a release, but you can grab them from the FTP and put out a fresh one.
